### ISSUE TITLE
mobile nav dropdown isn’t working

### ISSUE THREAD

**Issue by nohr** [paredol/mama#2]
tried to make a pure tailwind dropdown for the mobile nav but its not working. gonna have to look into it or handle with js

[Slack Message](https://paredol.slack.com/archives/C04BKFF6TJS/p1671727035796359)

**Comment by julesbibonimana** [comment]
Could we use Ant Design for this? We don't need to reinvent the wheel if there's already a solution that works.

**Comment by nohr** [comment]
we can definitely use that. it would be good for basic components, then use tailwind for custom styling if that's cool with you?

**Comment by julesbibonimana** [comment]
Yeah, bro. We don't need to reinvent the wheel. It's software, so we can use the frameworks many people have used before us and go from there.
